ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.vstorchevyi.skilky.ApplicationKt.module ]
    }
}

skilky {
    api {
        version = "1.0.0"
    }
    cors {
        allowedHosts = "*"
        allowedHosts = ${?SKILKY_CORS_ALLOWED_HOSTS}
    }
}
